@baseUrl = http://localhost:3001/api/blogs

### Get all blogs
GET {{baseUrl}}

### Login to be able to post a blog
# @name login
@token = {{login.response.body.$.token}}
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Author",
    "password": "author"
}

### Post a blog
# @name postBlog
@id = {{postBlog.response.body.$.id}}

POST {{baseUrl}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "Title",
    "author": "Author",
    "url": "url",
    "likes": 0,
    "userId": "64822318973c7147f952929e"
}

### Update the posted blog

PUT {{baseUrl}}/{{id}}
Content-Type: application/json

{
    "title": "This",
    "author": "Is",
    "url": "Updated",
    "likes": 1
}

### Delete the posted a blog
DELETE {{baseUrl}}/{{id}}


